spring:
  application:
    name: sample-boot-app
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

server:
  port: 18080

management:
  endpoints:
    web:
      exposure:
        include: health,info

component:
  exception:
    enabled: true
    include-path: true
    expose-stack-trace: false
    default-error-code: INTERNAL_ERROR
